require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - bin/**/*
    - db/**/*
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - config/**/*

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Max: 12
